CREATE TABLE Transactions (
    Transaction_ID VARCHAR(50) PRIMARY KEY,
    Transaction_Date DATE NOT NULL,
    Transaction_Time TIME NOT NULL,
    Time INT,
    Amount FLOAT NOT NULL CHECK (Amount > 0),
    Card_Type VARCHAR(20),
    Country VARCHAR(50),
    City VARCHAR(100),
    IP_Address VARCHAR(50),
    Merchant_ID VARCHAR(50),
    Merchant_Category VARCHAR(50),
    Transaction_Mode VARCHAR(20),
    Auth_Method VARCHAR(20),
    Device_Type VARCHAR(20),
    Transaction_Status VARCHAR(20),
    Currency VARCHAR(10),
    Card_Issuer VARCHAR(50),
    Customer_Segment VARCHAR(20),
    Fraud_Score FLOAT,
    Previous_Fraud_Flag INT CHECK (Previous_Fraud_Flag IN (0,1)),
    Is_Fraud INT CHECK (Is_Fraud IN (0,1)),
    created_at DATETIME DEFAULT GETDATE()
);